<a href="https://colab.research.google.com/github/LatiefDataVisionary/matplotlib-with-indonesia-belajar/blob/main/Matplotlib_15_Belajar_3D_Area_Plot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Matplotlib 15: Belajar 3D Area Plot | 3D Area Chart | Belajar Matplotlib Dasar | Visualisasi Data**


In [2]:
import matplotlib
import matplotlib.pyplot as plt
import numpy as np

print(matplotlib.__version__)
print(np.__version__)

3.10.0
2.0.2


### **Sample Dataset**

In [3]:
n = np.linspace(-3.0, 3.0, 100)

x, y = np.meshgrid(n, n)
z = np.sqrt(x**2 + y**2)

In [7]:
x

array([[-3.        , -2.93939394, -2.87878788, ...,  2.87878788,
         2.93939394,  3.        ],
       [-3.        , -2.93939394, -2.87878788, ...,  2.87878788,
         2.93939394,  3.        ],
       [-3.        , -2.93939394, -2.87878788, ...,  2.87878788,
         2.93939394,  3.        ],
       ...,
       [-3.        , -2.93939394, -2.87878788, ...,  2.87878788,
         2.93939394,  3.        ],
       [-3.        , -2.93939394, -2.87878788, ...,  2.87878788,
         2.93939394,  3.        ],
       [-3.        , -2.93939394, -2.87878788, ...,  2.87878788,
         2.93939394,  3.        ]])

In [4]:
x.shape

(100, 100)

In [8]:
y

array([[-3.        , -3.        , -3.        , ..., -3.        ,
        -3.        , -3.        ],
       [-2.93939394, -2.93939394, -2.93939394, ..., -2.93939394,
        -2.93939394, -2.93939394],
       [-2.87878788, -2.87878788, -2.87878788, ..., -2.87878788,
        -2.87878788, -2.87878788],
       ...,
       [ 2.87878788,  2.87878788,  2.87878788, ...,  2.87878788,
         2.87878788,  2.87878788],
       [ 2.93939394,  2.93939394,  2.93939394, ...,  2.93939394,
         2.93939394,  2.93939394],
       [ 3.        ,  3.        ,  3.        , ...,  3.        ,
         3.        ,  3.        ]])

In [5]:
y.shape

(100, 100)

In [9]:
z

array([[4.24264069, 4.20000437, 4.15781429, ..., 4.15781429, 4.20000437,
        4.24264069],
       [4.20000437, 4.15693077, 4.11429901, ..., 4.11429901, 4.15693077,
        4.20000437],
       [4.15781429, 4.11429901, 4.07122086, ..., 4.07122086, 4.11429901,
        4.15781429],
       ...,
       [4.15781429, 4.11429901, 4.07122086, ..., 4.07122086, 4.11429901,
        4.15781429],
       [4.20000437, 4.15693077, 4.11429901, ..., 4.11429901, 4.15693077,
        4.20000437],
       [4.24264069, 4.20000437, 4.15781429, ..., 4.15781429, 4.20000437,
        4.24264069]])

In [6]:
z.shape

(100, 100)